### ISSUE TITLE
inactive development

### ISSUE THREAD

**Issue by Suburbanno** [alessandrojean/toshokan-android#18]
Hey, do you still intend to return to maintain the project someday? I would like to test

**Comment by alessandrojean** [comment]
Short answer: yes, eventually.

I am currently focusing my efforts into writing a new proper self-hosted tool so any clients can use its API instead. When its stable I plan to change this app to be a client instead of handling all database stuff locally.

I have no ETA though, this is just a hobby project which is taking slow steps in its development as I don't have much time to work on it right now.

Thanks for the interest though, appreciated.
